name: fakelab_records_bot
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/git-electron/fakelab_records_bot

environment:
  sdk: ^3.4.1

dependencies:
  dotenv: ^4.2.0
  logger: ^2.4.0
  get_it: ^8.0.0
  slang: ^3.32.0
  freezed: ^2.5.7
  teledart: ^0.6.1
  injectable: ^2.5.0
  firebase_dart: ^1.2.2
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
