name: fakelab_records_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  teledart: ^0.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
